name: Makefile CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    # Currently configurish is not a big deal...
    #- name: configure
    #  run: ./configure

    - name: Build
      run: make

    #- name: Run check
    #  run: make check

    #- name: Run distcheck
    #  run: make distcheck
